package third_party_tests.gae;

import com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig;
import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static third_party_tests.gae.OfyService.ofy;

/**
 * Created by zaqwes on 5/7/14.
 */
public class CarOneToManyTest {
  private static final LocalServiceTestHelper helper =
    new LocalServiceTestHelper(new LocalDatastoreServiceTestConfig());

  static int RED = 90;
  static int BLUE = 89;

  @Before
  public void setUp() {
    helper.setUp();
  }

  @After
  public void tearDown() {
    helper.tearDown();
  }

  @Test
  public void testCoupling() {
    // https://code.google.com/p/objectify-appengine/wiki/Introduction
    // Fill
    CarOneToMany porsche = new CarOneToMany("2FAST", RED);
    ofy().save().entity(porsche).now();    // async without the now()
    assert porsche.id != null;    // id was autogenerated

    Engine engine = new Engine();
    // TODO: Need to save? Yes. Throw exception.
    ofy().save().entity(engine).now();
    porsche.setEngine(engine);

    ofy().save().entity(porsche).now();

    // Read

  }
}
