// Autogenerated
package frozen.dal.accessors_text_file_storage;

import java.util.List;
import java.util.Map;
public interface IndexCursor {
  void assignBranch(String branchName);
  void prIntegerBranch(String branchName);
  List<Map<String, Integer>> getSortedForwardIdx();
  void saveBranchCash();
  List<String> getListNodes();
  void processListContentSentences(List<String> sentences);
}