// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py
package to_text;

// Import
import java.util.List;

// App
import to_text.IExtracitorResourcePlan;
import to_text.IExtractorTextFromResource;
import to_text.ITextToText;
import to_text.IErrorContainer;

public interface /*class*/ IExtractorTextFromResource /* implement IExtractorTextFromResource */ {
    /** Соединяется с ресурсом и преобразовывает его в текст.
      Thinks:
        Не забывать освободить ресурсы(о реализации), но как быть при множ. наследовании
    */
    // Выделяет весь текст из ресурса по некоторому адресу
    // @param url в переменной все данные, чтобы ресурс мог быть открыт
    String extract(String url, IErrorContainer err);//hided {}

    // Получить из ресурса сразу список единиц контента - предложений, например
    List<String> contentItemsToList(String url, IErrorContainer err);//hided {}
}  // IExtractorTextFromResource