package frozen.abstractions;// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py



@Deprecated
public interface /*class*/ ErrorContainer /* implement frozen.abstractions.ErrorContainer */ {
    /**
      Thinks:
        Как я понял в Java нельзя передать примитив по ссылке, исключениями для обработки ошибок
          пользоваться не хочу - исключения для исключительных ситуаций.

        Можно как-то вернуть tuple, но похоже с python это не склеить
    */
    String what();//frozen {}
    int getErrCode();//frozen {}
}  // frozen.abstractions.ErrorContainer