package strange_things;// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py



public interface /*class*/ IErrorContainer /* implement strange_things.IErrorContainer */ {
    /**
      Thinks:
        Как я понял в Java нельзя передать примитив по ссылке, исключениями для обработки ошибок
          пользоваться не хочу - исключения для исключительных ситуаций.

        Можно как-то вернуть tuple, но похоже с python это не склеить
    */
    String what();//hided {}
    int getErrCode();//hided {}
}  // strange_things.IErrorContainer