package strange_things;// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py

// Import
import strange_things.IErrorContainer;

import java.util.List;


public interface ITextToText /* implement strange_things.ITextToText */ {
    // @param text зашумленнй текст, например html код
    // @return чистый текст
    // ! не возможно разрешить перегрузку
    String testToText(String text, IErrorContainer err);//hided {}

    // Получить сразу список единиц контента
    List<String> contentItemsToList(String text, IErrorContainer err);//hided {}
}  // strange_things.ITextToText
