package business.originator_frequency_index;

import java.util.List;

// Autogenerated
public interface IIndexCursor {
  void assignBranch(String branchName);
  void printBranch(String branchName);
  List<List<String, int>> getSortedForwardIdx();
  void saveBranchCash();
  List<String> getListNodes();
  void processListContentSentences(List<String> sentences);
}