package frozen.abstractions;// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py

// Import
import java.util.List;


public interface /*class*/ ExtractorTextFromResource /* implement frozen.abstractions.ExtractorTextFromResource */ {
    /** Соединяется с ресурсом и преобразовывает его в текст.
      Thinks:
        Не забывать освободить ресурсы(о реализации), но как быть при множ. наследовании
    */
    // Выделяет весь текст из ресурса по некоторому адресу
    // @param url в переменной все данные, чтобы ресурс мог быть открыт
    String extract(String url, ErrorContainer err);//frozen {}

    // Получить из ресурса сразу список единиц контента - предложений, например
    List<String> contentItemsToList(String url, ErrorContainer err);//frozen {}
}  // frozen.abstractions.ExtractorTextFromResource