package abstractions;// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py

// Import

import java.util.List;


public interface TextToText /* implement abstractions.TextToText */ {
    // @param text зашумленнй текст, например html код
    // @return чистый текст
    // ! не возможно разрешить перегрузку
    String testToText(String text, ErrorContainer err);//hided {}

    // Получить сразу список единиц контента
    List<String> contentItemsToList(String text, ErrorContainer err);//hided {}
}  // abstractions.TextToText
