// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py
package to_text;

// Import
import java.util.List;

// App
import to_text.IExtracitorResourcePlan;
import to_text.IExtractorTextFromResource;
import to_text.ITextToText;
import to_text.IErrorContainer;

public interface /*class*/ IErrorContainer /* implement IErrorContainer */ {
    /**
      Thinks:
        Как я понял в Java нельзя передать примитив по ссылке, исключениями для обработки ошибок
          пользоваться не хочу - исключения для исключительных ситуаций.

        Можно как-то вернуть tuple, но похоже с python это не склеить
    */
    String what();//hided {}
    int getErrCode();//hided {}
}  // IErrorContainer