// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py
package to_text;

// Import
import java.util.List;

// App
import to_text.IExtracitorResourcePlan;
import to_text.IExtractorTextFromResource;
import to_text.ITextToText;
import to_text.IErrorContainer;

public interface /*class*/ IExtracitorResourcePlan /* implement IExtracitorResourcePlan */ {
    /** Как бы навигационная часть */
    // Спорный вызов. Как он будет использоваться при множественном наследовании?
    // Захватывает точку входа в ресурс (например, файл базы данных)
    IErrorContainer captureRoot(String urlRoot);//hided {}
    // Error _freeRoot();  // должен вызывать в деструкторе

    // @param url информация о том, как можно добраться до вершины ресурса
    // @return карта, по которой можно передвигаться
    IGraphToText getPlan(String url, IErrorContainer err);//hided {}

    IGraphToText getPlanFromText(String url, IErrorContainer err);//hided {}

    // @return просто список "адресов"
    // Обобщить дробилку с рекурсией! Она использовалась для разбора страницы Курсеры
    List<String> getListAddresses(String url, IErrorContainer err);//hided {}

    // Выделяем адреса без подключения, у нас есть текст, который доставерно
    //   отражает план ресурса
    List<String> extractListAddressesFromText(String text, IErrorContainer err);//hided {}
}  // IExtracitorResourcePlan