// coding: utf-8
// Autogenerated by script D:\github\to-text\mkts\mkt_parser.py
package to_text;

// Import
import java.util.List;

// App
import to_text.IExtracitorResourcePlan;
import to_text.IExtractorTextFromResource;
import to_text.ITextToText;
import to_text.IErrorContainer;

public interface ITextToText /* implement ITextToText */ {
    // @param text зашумленнй текст, например html код
    // @return чистый текст
    // ! не возможно разрешить перегрузку
    String testToText(String text, IErrorContainer err);//hided {}

    // Получить сразу список единиц контента
    List<String> contentItemsToList(String text, IErrorContainer err);//hided {}
}  // ITextToText
