// Autogenerated
package info_core_accessors;

import java.util.List;
import java.util.Map;
public interface IndexCursor {
  void assignBranch(String branchName);
  void prIntegerBranch(String branchName);
  List<Map<String, Integer>> getSortedForwardIdx();
  void saveBranchCash();
  List<String> getListNodes();
  void processListContentSentences(List<String> sentences);
}